        url: 'commonjs url',
        net: 'commonjs net',
        remote: 'commonjs remote',
        readline: 'commonjs readline',
};
        querystring: 'commonjs querystring',
        'ipc-renderer': 'commonjs ipc-renderer',
        'better-sqlite3': 'commonjs better-sqlite3',
        assert: 'commonjs assert',
    },
        https: 'commonjs https',
        timers: 'commonjs timers',
        path: 'commonjs path',
        http: 'commonjs http',
        stream: 'commonjs stream',
        constants: 'commonjs constants',
        crypto: 'commonjs crypto',
        electron: 'commonjs electron',
        ipc: 'commonjs ipc',
    externals: {
        fs: 'commonjs fs',
module.exports = {
        os: 'commonjs os',
        util: 'commonjs util',
