        public searchBoxIcon: string,
        public contextMenuSeparators: string,
        public mainBackground: string,
        public primaryButtonText: string,
        public secondaryButtonBackground: string,
        public selectedItemBackground: string,
        public buttonBorder: string,
        public paneSeparators: string,
        public secondaryButtonText: string,
        public scrollBars: string,
        public sliderBackground: string,
        public highlightForeground: string,
        public windowButtonIcon: string,
        public headerBackground: string,
    public constructor(
}
        public searchBox: string,
        public settingsSeparators: string,
        public tooltipText: string,
        public headerSeparator: string,
export class ThemeNeutralColors {
        public selectedTabText: string,
        public footerBackground: string,
        public tabText: string,
        public sidePaneBackground: string,
        public sliderThumbBackground: string,
        public primaryText: string,
        public albumCoverBackground: string,
        public secondaryText: string,
    ) {}
        public searchBoxText: string,
        public dialogBackground: string,
        public hoveredItemBackground: string,
